### PR TITLE
VGM export for various chip targets

### PR DESCRIPTION
**Pull request by jpcima**
#98
 
Add to VGM exporter an ability to output for a different chip, or separate AY chip.
Dialog is updated and displays feature availability for the target.

- FM : OPNA, OPN2, OPN
- SSG : Internal, AY8910, YM2149

YM2203 can use internal SSG but will be at different clock setting.

**Note:** I should really clean up the garbage register writes for chip other than OPNA

**Edit1:** have mixed up AY8910 type & flag fields, fixed
**Edit2:** rebased on master, eliminated conflict

### CODE REVIEW

**Comment by jpcima** [comment]
This is correct. When it comes to register-level, I have not done the inventory of what bits may or may not be in use, and considered it fine (probably?) if they pass through regardless.
I have set up the filter for cases where it saves space in the file.

I believe also that not all have the flag "AM enable" for example.

**Comment by jpcima** [comment]
Judging from a look at MAME code, this register will surely interfere, so yes I'll mask it.

**Comment by rerrahkr** [comment]
It works well, thanks for your contribution!

**Comment by OPNA2608** [comment]
In hindsight, I don't know how I feel about this. I don't think it's really within the scope of this project to support the YM2612 or standalone AY-3-8910, especially when there are far more capable trackers for those already.

**Comment by cyberic99** [comment]
> especially when there are far more capable trackers for those

I do not know any working tracker for YM2612, do you have a link?

For YM2149, there are some native trackers on Atari ST, sur as Maxymizer, MusicMon, Checktrakk...

But there are not a lot of modern trackers working on the 3 major platforms...
I only know about Archos Tracker 2
And it is not open source

So... I too think that there is still room for BambooTracker

(I could have forgotten some other trackers I do not know about... feel free to complete my comment)

**Comment by jpcima** [comment]
>support the YM2612 or standalone AYs, especially when there are far more capable trackers for those already?

Personally, I've wanted to research for a workflow for AY tunes which favors use of free software only.
With such an option, it's possible.

On a Garvuino with atmega AY emulator synth, it opens a possibility. Previously, only Arkos Tacker and Vortex Tracker II have been available for this work.
BambooTracker has received a mention in the [Garvuino manual](https://github.com/farvardin/garvuino/blob/4d7331d8405181ec60dda9ae2a3b9744584d01a7/doc/garvuino_manual.t2t#L234).

Also the compatibility within the OPN family is nice to take advantage of; Mucom88's example is to consider, which has been used for Megadrive music.

**Comment by papiezak** [comment]
>I do not know any working tracker for YM2612, do you have a link?

@cyberic99 There is DefleMask. Available on Mac, Windows, Linux, and very recently iOS and Android. Closed-source, development seems to have stopped around 2016, except mobile versions. Supports VGM logging, CH3 special mode, has MIDI input feature. It also supports YM2151, SID( a bit glitchy), Gameboy sound hardware, Master System's PSG, etc...

**Comment by cyberic99** [comment]
> There is DefleMask

Yes right.

I knew it could export to ym2151 but forgot about ym2612.

The devs seem to promote the mobile version, but as you say the desktop version is lagging.
And there are many bugs.

If deflemask was open source, I think that many f these bugs would have been fixed and that it could have received a lot of help from the community.

And Deflemask doesn't support ym2149.

Deflemask has a lot of potential, and changing the systems while keeping the notes data is very useful.

But as of today, is is no more maintained.
And I find the UI confusing sometimes, and some actions are a bit strange (like using the middle click button), or accidental click increases the column number...

**Comment by OPNA2608** [comment]
> There is DefleMask

> development seems to have stopped around 2016, except mobile versions

> But as of today, is is no more maintained.

[DefleMask](http://deflemask.com/) is still in active development afaik. As we're speaking, they're doing a poll on what system to ~bloat their software package with~ **add next** :confused:. It's not open-source yet, but they aim for going there "eventually". In the future. Supposedly.

I don't know where you all got the idea that it has seized development?

> For YM2149
> But there are not a lot of modern trackers working on the 3 major platforms...

YM2149 and AY stuff in general? Anyone I know that composes for those kind of chips either use native trackers, Arkos, Vortex II or 0CC-FamiTracker with the S5B expansion. Those who have tried BambooTracker for this use-case found it less useful command-wise than the alternatives. Furthermore, VGM is not exactly the most popular AY song format.

> Also the compatibility within the OPN family is nice to take advantage of;

But does BambooTracker really *need* to become the next DefleMask, a "jack of all trades, master of none" wanting to support *all teh chips*? Is aiming for universal OPN-family support really within the scope of BambooTracker :confused:? @rerrahkr 

> BambooTracker is a music tracker for the Yamaha YM2608 (OPNA) sound chip which was used in NEC PC-8801/9801 series computers.

**Comment by papiezak** [comment]
>DefleMask is still in active development afaik. As we're speaking, they're doing a poll on what system to bloat their software package with add next

The same poll was over three years ago, OPL2/OPL3 has won if I remember correctly 🤣 I don't think devs added anything like that, same with many other glorious features  🙄 

>But does BambooTracker really need to become the next DefleMask, a "jack of all trades, master of none" wanting to support all teh chips?

Well, IMO BambooTracker should perfect and polish YM2608 system support as much as it's possible, then _maaaaaybe_ add YM2203 or anything else.

**Comment by pedipanol** [comment]
>But does BambooTracker really need to become the next DefleMask, a "jack of all trades, master of none" wanting to support all teh chips? Is aiming for universal OPN-family support really within the scope of BambooTracker 😕?

@OPNA2608 The reason I requested other soundchip exports was because YM2203 (note that I didn't request YM2612) and YM2419 export could be implemented without interfering on the focus of the tracker. I didn't mean for it to become jack of all trades, just for it to become a master of OPNA while giving other options that wouldn't disrupt the workflow of the tracker itself.

It would be simply exporting the VGM files in other compatible formats, no change in the core of the tracker itself. Which is different from deflemask's multichip support, that requires a complete change in emulation for each extra soundchip.

This is why I dismissed when someone mentioned OPM support, it's a completely different soundchip that would require a lot of work to implement.

I _did_ request the ability to hide unused channels, but it's just that: hide. It's something I want even for making OPNA stuff, considering I personally barely use Rhythm.

**Comment by jpcima** [comment]
@OPNA2608 it's as @pedipanol said above, exporting is very different, and I am also entirely against the idea of having the multi-chip. I think to characterize the feature as such is a vast exaggeration.
Possibly, it may belong in some "advanced" section out of the view of regular users; without too much doubt, it remains a marginal use case.

**Comment by OPNA2608** [comment]
> (also YM2203 was a soundchip used in the NEC PC-x801 series)

Hence the YM2203 is the only one I think we should really target in addition to the YM2608. Along with volume presets to simulate the differences between the PC-9801-86 and SpeakBoard, it would cover all of the PC-9800 series' sound options most people would care about. (Beeper and generic Windows-era PCM audio aside).

But it shouldn't be a priority for now, as you can easily simulate the YM2203's feature set by just not using FM4-6, ignoring the Rhythm module and sticking to Mono panning, whereas the YM2608 in BambooTracker is still lacking ADPCM capabilities.

> I think to characterize the feature as such is a vast exaggeration.

It sends the mixed signal of BambooTracker now also supporting / working on supporting the YM2612, I saw discussions like that on Discord servers I use and on Twitter.

**Comment by rerrahkr** [comment]
The reason I began creating BambooTracker is that there was no tracker of YM2608 (and YM2203) as far as I know, so I think YM2608 is the principal target of the tracker. Since YM2608 have YM2203 mode, it is not difficult to support YM2203.
I think YM2608 is an extension of YM2203, however, since the YM2608 and YM2612 have differences in SSG and PCM, different emulations are required. In addition, there is also a YM2612 tracker, so I will not do full support for YM2612. However it were able to export FM and SSG channels to YM2612 vgm at the moment, I added only limited export function.

**Comment by jpcima** [comment]
>It sends the mixed signal of BambooTracker now also supporting / working on supporting the YM2612, I saw discussions like that on Discord servers I use and on Twitter.

It's understandable why this can be a problem. I wouldn't mind really if YM2612 is hidden at present time.

1. about export limitations, I did my best effort to make this clear on the user interface, in eye catching manner. But the meaning is not explicited in textual way, a reason why users may interpret it with confusion.
2. on the YM2612 export specifically, the result will be only as intented when clock is matching to what BambooTracker uses; it would work on a software VGM player which can set clock as desired, but a user may expect it to work on Megadrive and it will fail, creating more confusion.
(There existed machines which run OPN2 at matching clock, but MD is not among them)

**Comment by OPNA2608** [comment]
You can already convert YM2608 to YM2612 VGMs (FM-only ofc) and YM2149 (integrated) to AY, the tools required are public and work on Windows and Linux as well, all it took on Linux was to disable the stack smashing detection for the main executable to run. One of the tools is an f-number converter to a clock rate of your choice to make them hardware-compatible too.
https://youtu.be/Yr5-2-w5eRE

**Comment by jpcima** [comment]
@OPNA2608 Well yes, I'm well aware, but the approach is imperfect and has timbre distorsion.

**Pull request merged**
