### PR TITLE
Midi

### PR DESCRIPTION
**Pull request by jpcima**
#32

Adds MIDI input support for note entry, in edit mode and in jam mode.

### CODE REVIEW

**Comment by jpcima** [comment]
Adding `libasound2-dev` should fix Travis-CI.

**Comment by rerrahkr** [comment]
I added `sudo apt install libasound2-dev` in .travis.yml at 8b762d141d18e476a06bc65d6ef27a548dbcea1a.

**Comment by jpcima** [comment]
This did the job thanks. I didn't realize I could do this myself.
Rebased the work on the `master` branch.

**Comment by jpcima** [comment]
Rebased the work on current `master`.
Congrats @rerrahkr on the new 0.1.6 release.

**Pull request merged**
