### PR TITLE
French L10n

### PR DESCRIPTION
**Pull request by jpcima**
This is the :fr: translation. All strings are done, but some verification will be nice.
Expecting for @trebmuh to validate and give us the green light.

I reworked a few elements of sources.
- "notr" where appropriate
- I have named or renamed current toolbars, which appear in the right click context menu: `Main toolbar`, `Secondary toolbar`.

**Also**: please consider PR #61 to help have a working build process for most setups.

### CODE REVIEW

**Comment by trebmuh** [comment]
Pretty much all good for me. @jpcima I made a PR with a few improvements/fixes, after what, everything looks fine to me and is ready to be merged here from my POV.

**Comment by jpcima** [comment]
I believe it's fine to merge at this current state, you can go ahead.

It's still been on discussion whether individual contents of the PR above are actually appropriate, and personnally I think they aren't; we can make a followup PR happen if needed.
Current state is fine, it's not necessary to put it on wait.

**Comment by trebmuh** [comment]
OK for merging it as is.

**Comment by rerrahkr** [comment]
Thanks for your contributions!

**Pull request merged**
