### PR TITLE
Separation of data and code

### LINKED ISSUE #264: [macOS|Linux|BSD] - Localized manpages get installed to wrong directory
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

We currently install the manpages like so:

`$PWD/../BambooTracker*.1 -> $PREFIX/share/man/man1/`

Which usually dumps all manpages into one directory.

`/usr/share/man/man1/BambooTracker.1`
`/usr/share/man/man1/BambooTracker.fr.1`

According to [these specs for manpages](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html#idm236091757632), they should be moved into language-specific subdirectories:

`/usr/share/man/en/man1/BambooTracker.1`
`/usr/share/man/fr/man1/BambooTracker.1`

You can assign this issue to me and I'll get around to fixing this eventually. Unless someone else's quicker ofc. :sweat_smile: 

## How to reproduce

See [BambooTracker/BambooTracker.pro](https://github.com/rerrahkr/BambooTracker/blob/ce9eb30e88b292cf08c65302b14d8718e26c734c/BambooTracker/BambooTracker.pro#L603-L605).

## System Information

- **Operating System**: NixOS 20.03 (Markhor) x86_64
- **BambooTracker Version**: v0.4.4
- **Build Type**: Via package manager

### PR DESCRIPTION
**Pull request by OPNA2608**
This should be merged before #271 so that one can be rebased on the install system improvements introduced here.

This PR is quasi-done, only AppVeyor fixing and some non-critical cleanup in CI scripts & deploy repo & API key is missing. Test releases [here](https://github.com/OPNA2608/BambooTracker/releases/tag/v0.5.1).

---

This PR attempts to physically & logically separate all non-code data from the BambooTracker C/C++ code. This is achieved by both moving the data in one common `/data` directory and data-focused QMake project files spread throughout it with an `include` statement in the main `BambooTracker.pro`. I also took the chance to add some further data-specific improvements including fixing the manpage install paths, setting up optional `minimal` and `flat` installation options and adding a macOS iconset.

If this is too much at once for you and you'd prefer if i split this up into multiple commits / PRs or you disagree with some of these decisions, please let me know!

Closes #264.

grafik

---

Summary from commit:

- moves all the non-code data into a separate top-level `data` directory
- adds more QMake code to wire everything together
- introduce additional `CONFIG` flags `install_minimal` and `install_flat` to control
  how many non-essential data files are being installed and where everything will be installed to
  in relation to `PREFIX`
- Travis CI using `make install` & `install_flat` options to simplify CI packaging scripts (TODO: AppVeyor)
- adds macOS-specific `BambooTracker.icns` app icon

### CODE REVIEW

**Comment by OPNA2608** [comment]
Note: BambooTracker.icns needs to be regenerated. I only placed the 16x16 and 256x256 versions found in our repository in it, but I read the original icon submission again and @Decidetto's intention was to scale & use the 256x256 version for all but the 16x16 size.

>  Do make sure that the 256×256 version is used for all resolutions but 16×16.

 I'll redo the iconset structure and send it to a friend with macOS to redo the icns file later today.

**Comment by OPNA2608** [comment]
Fixed AppVeyor & tested (Windows) builds, added more resolutions of the app icon and regenerated the macOS icns to have more available resolutions. If CI passes, I'll do a test release on my fork. If that one works fine, I'll revert my fork-specific overrides for deploying and squash the commits.

**Comment by OPNA2608** [comment]
Test releases [here](https://github.com/OPNA2608/BambooTracker/releases/tag/v0.5.1), let me know if you see any problems with them. If everything looks okay I'll pretty up the commits and force-push, then you can merge everything and I'll rebase #271.

**Comment by rerrahkr** [comment]
As far as I checked they works well.
By the way, don't you rename the directory `BambooTracker` to `src` in this PR? I tried the same change in [another Qt project](https://github.com/rerrahkr/YM2608-Tone-Editor) and it worked fine.

**Comment by OPNA2608** [comment]
Tested on macOS, ran fine.

> By the way, don't you rename the directory `BambooTracker` to `src` in this PR?

I was hurrying to get this PR done so we can make another release soon. It's fine for now, but yes, I'll make that change & a top-level project file in the future.

**Comment by rerrahkr** [comment]
Thanks for your contribution!

**Pull request merged**
