### PR TITLE
Improve misc file installation

### LINKED ISSUE #248: [Linux|BSD?] - Most misc. files not installing by default
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Currently, of the miscellaneous files intended for distribution, `make install` only installs the translation files. This leaves it up to the package maintainers to remember to move the rest of the files (desktop file, man pages, demos, skins, icons, licenses & LICENSE(?)) into the corresponding directories.

Example of my post-`make install` workaround for Nixpkgs to get all files installed in the proper directories:
grafik

I'll tinker on this over the weekend. Should be fairly straight-forward, I'm looking at https://github.com/buddhi1980/mandelbulber2/blob/a9ada7179be2ebeb907e13baa9c8c71c937f2ba1/mandelbulber2/qmake/installer.pri#L13-L46 as an example.

## How to reproduce

1. git clone && cd BambooTracker/BambooTracker
2. mkdir test && qmake PREFIX=$PWD/test && make && make install
3. tree test

grafik

## System Information

- **Operating System**: Ubuntu 18.04.4 LTS x86_64
- **BambooTracker Version**: v0.4.3
- **Build Type**: Locally, Package manager (apt, nix)

### PR DESCRIPTION
**Pull request by OPNA2608**
Closes #248.

On Linux/BSD systems, attempt to install all the miscellaneous files into various directories under `$$PREFIX/share`, depending on the file:

- man pages -> `man/man1`
- desktop file -> `applications`
- icons -> `icons/hicolor/$${iconsize}x$${iconsize}/apps`
- everything else (licenses, demos, skins) -> `BambooTracker`

Automatically installed files, without any `postInstall` script now:
grafik

### CODE REVIEW

**Comment by OPNA2608** [comment]
Working on resolving the CI failures. Aside from that, please don't merge yet. I forgot about the use-case of a system-wide, non-AppBundle installation, as would be the case in Nixpkgs.

**Comment by OPNA2608** [comment]
I think this should work, don't have a Mac to test this though.

Current CI failure seems unrelated, some aborted connection while uploading the artifact.

**Comment by OPNA2608** [comment]
Apparently documentation and licenses are kept in `/usr/share/doc/${package_name}/` by convention, you never stop learning new things. Will update accordingly soon.

**Comment by rerrahkr** [comment]
I can't test, but is it okay to merge?

**Comment by OPNA2608** [comment]
There's a single thing I'm not quite happy with yet. The install process will end up dropping a "BambooTracker.png" file in the project file directory, because we need to rename the icons from `icon_${dimension}.png` to `BambooTracker.png` so they can be installed in the appropriate `share/icons/hicolor/${dimension}/apps/` directory and the default install method via `.files -> .path` does not support this. This image is never properly cleaned up, which is sort of a bummer. I want to ponder over this a little bit more first, if you don't mind. Maybe I'll write a custom install target without the default behaviour or restructure the files in the repo to already follow this directory pattern and see if there's any fallout from such a change.

Also, CC @jpcima @alexmyczko because I believe you maintain various distros' packages for BambooTracker. Do these improvements look good to you? ~~(And OT but you might have to take another look at your qmake invocations since we changed how available [but not at runtime required] sound APIs are configured. Your packages only support the default ALSA option as-is afaik.)~~

**Comment by rerrahkr** [comment]
Now, I noticed in #51 that @ehaupt asked me to do the following:

> Would it be possible to include this file as **BambooTracker.png** in the icon directory?

But I didn't read the question correctly so it seems to have caused this problem. I'm sorry.

If Linux/BSD systems store all the icons in `share/icons/hicolor/${dimension}/apps/`, how about putting each image in `res/icon/app_icon/16x16/BambooTracker.png` and `res/icon/app_icon/256x256/BambooTracker.png`?

**Comment by OPNA2608** [comment]
> how about putting each image in `res/icon/app_icon/16x16/BambooTracker.png` and `res/icon/app_icon/256x256/BambooTracker.png`?

That would be great, yeah. Is it enough if I do that or are there any other bits of code that'd need to be changed for that?

**Comment by rerrahkr** [comment]
Those 2 images are only used for packaging, so there is no need to change the source while you change them.

**Comment by OPNA2608** [comment]
> I can't test, but is it okay to merge?

I'll give this one last test later just to make sure everything's working as intended, I'll let you know when it's okay to merge.

**Comment by OPNA2608** [comment]
LGTM, I believe this should all be in the proper directories now.

<details>
<summary>tree listing of the installed files</summary>

```
/nix/store/hh7aryzjfqc9n9p5brphr46qky7nd4md-bambootracker-unstable-2020-08-10/
├── bin
│   └── BambooTracker
└── share
    ├── applications
    │   └── BambooTracker.desktop
    ├── BambooTracker
    │   ├── demos
    │   │   ├── demos.md
    │   │   ├── instruments
    │   │   │   ├── papiezak
    │   │   │   │   ├── FM.btb
    │   │   │   │   └── SSG.btb
    │   │   │   ├── Rerrah
    │   │   │   │   ├── FM.btb
    │   │   │   │   ├── PMD-like Drums.btb
    │   │   │   │   └── SSG.btb
    │   │   │   └── Takeshi Abo
    │   │   │       ├── Bass.btb
    │   │   │       ├── Bell.btb
    │   │   │       ├── Brass.btb
    │   │   │       ├── Guitars.btb
    │   │   │       ├── Lead & Organ.btb
    │   │   │       ├── Percussion.btb
    │   │   │       ├── Piano.btb
    │   │   │       ├── Sound Effect.btb
    │   │   │       ├── Special.btb
    │   │   │       ├── Strings & Pad.btb
    │   │   │       ├── Wind.btb
    │   │   │       └── World.btb
    │   │   └── modules
    │   │       ├── Battleship.btm
    │   │       ├── breeze 2608.btm
    │   │       ├── Is This What You Desired.btm
    │   │       ├── Lotus.btm
    │   │       ├── Neo Megalopolis.btm
    │   │       ├── No Time To Waste.btm
    │   │       ├── Rude Buster.btm
    │   │       ├── sword with no scabbard.btm
    │   │       ├── Underwater Ruins.btm
    │   │       └── Wild Battle (RSE).btm
    │   ├── lang
    │   │   ├── bamboo_tracker_fr.qm
    │   │   └── bamboo_tracker_ja.qm
    │   └── skins
    │       ├── Cream.ini
    │       ├── Default-Blue.ini
    │       ├── Default.ini
    │       ├── Dynagray.ini
    │       ├── FTish.ini
    │       └── Night Blue.ini
    ├── doc
    │   └── BambooTracker
    │       ├── LICENSE
    │       └── licenses
    │           ├── c86ctl_lisence.txt
    │           ├── list.md
    │           ├── mame_license.txt
    │           ├── rtaudio_license.txt
    │           ├── rtmidi_license.txt
    │           └── scci_license.txt
    ├── icons
    │   └── hicolor
    │       ├── 16x16
    │       │   └── apps
    │       │       └── BambooTracker.png
    │       └── 256x256
    │           └── apps
    │               └── BambooTracker.png
    └── man
        └── man1
            ├── BambooTracker.1.gz
            └── BambooTracker.fr.1.gz

23 directories, 49 files
```
</details>

**Comment by rerrahkr** [comment]
Thanks for your contributions!

**Pull request merged**
