### PR TITLE
Change audio output stream

### PR DESCRIPTION
**Pull request by rerrahkr**
#49, #96
I'm trying to change audio output stream.
Conventionally sample generation has been performed according to the remaining amount of buffer, however in this, sample generation is performed using a timer. The timer is set its interval to the module tick frequency. When the timer is raised, the tracker counts up tick, updates ui, generates samples for one tick and flushes them to a buffer.  And buffer filed, it send to `QIODevice`.
It seems to solve stuttering of ui drawings in this, but the sound is choppy. 😕

### CODE REVIEW

**Comment by jpcima** [comment]
I have noticed about `QAudioOutput` as I tried to improve the audio situation:
it never uses `setBufferSize` on the audio object. Maybe increasing this buffer could help.

I believe the audio has essentially 2 problems:
- no tasks are separated, all are in a single thread
- the tick is on the Qt event loop and needs it to react fast, but there is not a notion of preemption or priority. so, ticks can be delayed by indefinite durations.

**Comment by rerrahkr** [comment]
I close this draft to separate audio task from main graphic thread before fixing stuttering of drawings.
I'm going to use a library such as RtAudio to handle audio tasks in a separate thread.

**Comment by jpcima** [comment]
I did work here a long ago, as an experiment, which ran audio in a separate thread.
It was unfinished, done as experiment, device selection was not done.

From what I remember of this experiment, this alone was not sufficient, it needed some deeper changes in the tracker engine itself, which I don't recall exactly from memory.

https://github.com/jpcima/BambooTracker/tree/audio-thread

**Comment by rerrahkr** [comment]
Thanks for your information! I will check your branch.

**Pull request closed without merging**
