### PR TITLE
Null-pointer based MIDI API check

### PR DESCRIPTION
**Pull request by rerrahkr**
#288 

replaced `RTMIDI_DUMMY` fallbacks

I fixed sources based on audio API initialization.

### CODE REVIEW

**Comment by OPNA2608** [comment]
Runs on a system without any exposed MIDI API, but brings up an "Unable to initialize MIDI!" error box on launch & any configuration change (similar to https://github.com/rerrahkr/BambooTracker/issues/172#issuecomment-569419413). There also is no option in the settings to just turn off MIDI (like with the Dummy API option previously) and thus no way of disabling this.

Would it be possible to either have a virtual "Off" API or (in my opinion cleaner) a checkbox to disable MIDI input (including the MIDI input options)?

**Comment by rerrahkr** [comment]
I think it's easy to implement the checkbox. I also try to change it to force midi input to be disabled if BT get a midi error.

**Comment by OPNA2608** [comment]
When I manually tick the MIDI checkbox, set an API that fails to initialize and press [OK] (doesn't happen with [Apply]?), the option disables itself after closing the error message. Is this intentional or accidentally being treated like a first launch & falling back to the "off" default? It feels inconsistent with how every other configuration option works. Audio in particular keeps the selected not-working API option instead which I think is preferable.

**Comment by rerrahkr** [comment]
BT intentionally turned off it when an error occurred, but i will change it. MIDI input is set to disabled on first launch, so it probably doesn't need the MIDI API fallback, and leave the internal value of config unchanged even if the MIDI API is in error.

**Comment by OPNA2608** [comment]
One last thing is that the device combobox doesn't get properly disabled when opening the configuration window. Toggling the MIDI checkbox to [x] -> [ ] once properly disables it.
grafik

> MIDI input is set to disabled on first launch

If possible, it'd be nice if the MIDI APIs could get automatically tested for a functional one on first launch, with "disabled" being the default if none of them are determined to be working. Similar to what we're doing with RtAudio but for RtMidi instead, so everything "Just Works:tm:" for new users and existing users transitioning to the next release won't be stumped by their MIDI device suddenly not working. We can move that into another feature request though if you'd rather just get the base functionality working for now, LGTM aside from this.

**Comment by rerrahkr** [comment]
Audio streaming is a must-have feature for everyone, but MIDI input is only used by people who have a MIDI keyboard, so I think it is better to turn off at the first time. Many software I know also set up MIDI I/O manually after startup.

**Comment by OPNA2608** [comment]
Hm, okay.

b208d50 didn't fix the problem afaict, combobox is still enabled upon opening Configuration dialogue. Qt5.9.5 & Linux if that helps with identifying the problem.

**Comment by rerrahkr** [comment]
> combobox is still enabled upon opening Configuration dialogue.

I was confused because such a problem did not occur on Windows, but I was able to reproduce it on macOS, so I fixed it. I'm not sure why it happens, maybe it's a Qt bug.

**Comment by OPNA2608** [comment]
Works but prints this on the terminal:

```
QMetaObject::connectSlotsByName: No matching signal for on_midiApiComboBox_currentIndexChanged(QString,bool)
```

**Comment by rerrahkr** [comment]
Oh I didn't notice the log. I've separated its method so I think this is okay.

**Review by OPNA2608 — APPROVED** [review]

**Comment by rerrahkr** [comment]
Thanks reviewing!

**Pull request merged**
