### PR TITLE
Migrate test & release CI from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by OPNA2608**
Closes #271. (version bumps and Linux release implemented here, README improvements via a follow-up PR)

Reason: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing. Will squash commits & add minor fix-ups soon.

### CODE REVIEW

**Comment by OPNA2608** [comment]
Working checks on my fork: https://github.com/OPNA2608/BambooTracker/commit/fc5ae7b0c3d6e4957d00df83ae68edfef461b25d/checks (2x every target, once as a commit and once as a release with upload)

Test release: https://github.com/OPNA2608/BambooTracker/releases/tag/v0.0.0

grafik

**Comment by rerrahkr** [comment]
Checked test release for Windows & Mac, they are worked fine on my environment. Would you mind me merging this PR?

**Comment by OPNA2608** [comment]
Go ahead, I cleaned everything up and squashed it into 1 commit. I hope the Actions start working by the next commit. :+1:

**Comment by rerrahkr** [comment]
Thanks for your contribution!

**Pull request merged**
